In [ ]:
# --face recognition using eigenface--

#code:  http://scikit-learn.org/stable/auto_examples/applications/plot_face_recognition.html#sphx-glr-auto-examples-applications-plot-face-recognition-py

# references: 1.   https://github.com/bugra/EigenFace
#             2.   https://github.com/junzis/memeit/blob/master/ref/face_recognition.py
#             3.   https://onionesquereality.wordpress.com/2009/02/11/face-recognition-using-eigenfaces-and-distance-classifiers-a-tutorial/
#             4.   http://bugra.github.io/work/notes/2013-07-27/PCA-EigenFace-And-All-That/

In [ ]:
#from __future__ import print_function      #allows incompatible function to run here
                                         # printing way

In [1]:
from time import time           #will display logging time/warning
import logging

In [2]:
import matplotlib.pyplot as plt
     #plotting the graph

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
from sklearn.model_selection import GridSearchCV
     #exhaustive searching over a grid of parameters

In [5]:
from sklearn.metrics import classification_report
        #generates matrix of target values 
       #pricision, recall, f1-score ,support (read sklearn)

In [6]:
from sklearn.metrics import confusion_matrix
      # for debugging confusion matrix

In [7]:
from sklearn.svm import SVC
      #support vector classification
      #svm part : fails for large datasets

In [8]:
from sklearn.datasets import fetch_lfw_people
       # taking dataset of people from sklearn dataset

In [9]:
from sklearn.decomposition import PCA
       #principal component analysis
       #linear dimension reduction using decomposition 
        

In [10]:
#print(__doc__)
     #it prints the module docstring but automatically in Ipython

In [11]:
logging.basicConfig(level=logging.INFO,format='%(asctime)s %(message)s')

In [12]:
import numpy as np
import pandas as pd


In [13]:
dataset=fetch_lfw_people(min_faces_per_person=100,resize=0.3)

In [14]:
dataset

{'DESCR': 'LFW faces dataset',
 'data': array([[  88.33333588,   64.33333588,   90.33333588, ...,  110.33333588,
          109.        ,  153.66667175],
        [  47.33333206,   71.33333588,  120.66666412, ...,  226.33332825,
          233.        ,  224.33332825],
        [  38.        ,   44.33333206,   84.33333588, ...,  102.66666412,
           90.66666412,   62.33333206],
        ..., 
        [ 224.        ,  208.33332825,  194.33332825, ...,  141.66667175,
          148.33332825,  158.33332825],
        [ 109.66666412,  134.33332825,  145.33332825, ...,  181.33332825,
          215.33332825,  186.        ],
        [  60.33333206,  115.        ,  108.33333588, ...,   10.66666698,
           24.        ,   31.33333397]], dtype=float32),
 'images': array([[[  88.33333588,   64.33333588,   90.33333588, ...,   85.        ,
           103.        ,   96.66666412],
         [  91.33333588,   71.33333588,  117.66666412, ...,   81.        ,
            85.        ,   94.33333588],
    

In [15]:
n_samples,h,w=dataset.images.shape

n_sapmples

In [16]:
n_samples

1140

In [17]:
h

37

In [18]:
w

28

In [19]:
dataset.images.shape

(1140, 37, 28)

In [20]:
dataset.images

array([[[  88.33333588,   64.33333588,   90.33333588, ...,   85.        ,
          103.        ,   96.66666412],
        [  91.33333588,   71.33333588,  117.66666412, ...,   81.        ,
           85.        ,   94.33333588],
        [  81.33333588,   91.        ,  130.33332825, ...,  105.        ,
           83.33333588,   77.66666412],
        ..., 
        [  48.        ,   53.33333206,   61.        , ...,   92.        ,
          108.66666412,  105.        ],
        [  26.        ,   33.66666794,   46.66666794, ...,  106.        ,
          104.        ,  107.66666412],
        [  26.66666603,   32.        ,   44.        , ...,  110.33333588,
          109.        ,  153.66667175]],

       [[  47.33333206,   71.33333588,  120.66666412, ...,  139.66667175,
           98.        ,   50.66666794],
        [  43.66666794,   82.        ,  138.        , ...,  145.        ,
          138.        ,   84.66666412],
        [  46.        ,   97.        ,  141.66667175, ...,  142.33332825

In [21]:
X=dataset.data

In [22]:
X

array([[  88.33333588,   64.33333588,   90.33333588, ...,  110.33333588,
         109.        ,  153.66667175],
       [  47.33333206,   71.33333588,  120.66666412, ...,  226.33332825,
         233.        ,  224.33332825],
       [  38.        ,   44.33333206,   84.33333588, ...,  102.66666412,
          90.66666412,   62.33333206],
       ..., 
       [ 224.        ,  208.33332825,  194.33332825, ...,  141.66667175,
         148.33332825,  158.33332825],
       [ 109.66666412,  134.33332825,  145.33332825, ...,  181.33332825,
         215.33332825,  186.        ],
       [  60.33333206,  115.        ,  108.33333588, ...,   10.66666698,
          24.        ,   31.33333397]], dtype=float32)

In [23]:
X.shape   #first one is faces and second is feature

(1140, 1036)

In [24]:
n_features=X.shape[1]    

In [25]:
n_features

1036

In [26]:
#for target values

In [27]:
y=dataset.target

In [28]:
y

array([2, 3, 1, ..., 4, 2, 4], dtype=int64)

In [29]:
target_names=dataset.target_names

In [30]:
target_names

array(['Colin Powell', 'Donald Rumsfeld', 'George W Bush',
       'Gerhard Schroeder', 'Tony Blair'],
      dtype='<U17')

In [31]:
target_names.shape

(5,)

In [32]:
n_classes=target_names.shape[0]

In [33]:
n_classes

5

In [34]:

#splitting the dataset

In [35]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [36]:
X_train

array([[  52.66666794,   66.33333588,   94.33333588, ...,   78.66666412,
          17.33333397,   20.        ],
       [ 197.33332825,  164.33332825,  140.66667175, ...,  177.33332825,
          53.33333206,   88.33333588],
       [  45.33333206,   54.        ,  142.66667175, ...,  232.33332825,
         233.66667175,  237.66667175],
       ..., 
       [  62.        ,   49.        ,   73.        , ...,  234.66667175,
         214.66667175,   83.66666412],
       [ 116.66666412,  126.33333588,  144.33332825, ...,   40.33333206,
          41.        ,   43.        ],
       [ 112.        ,  133.66667175,  147.66667175, ...,  176.        ,
          75.        ,   22.66666603]], dtype=float32)

In [37]:
y_train

array([2, 0, 0, 2, 2, 2, 2, 2, 4, 2, 0, 4, 2, 2, 4, 2, 2, 2, 2, 0, 2, 0, 0,
       1, 0, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 2, 0, 2, 2, 1, 0, 2, 2, 4, 0, 2,
       0, 3, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 4, 2, 2, 0, 2, 2, 2, 2, 0, 3,
       2, 0, 2, 2, 2, 3, 3, 2, 1, 2, 0, 0, 2, 3, 2, 4, 2, 2, 2, 1, 3, 2, 2,
       2, 4, 2, 4, 2, 2, 2, 3, 0, 2, 3, 2, 2, 2, 0, 2, 2, 0, 2, 3, 2, 2, 1,
       2, 2, 0, 2, 2, 0, 0, 1, 2, 0, 2, 0, 2, 0, 2, 4, 0, 4, 2, 2, 1, 0, 2,
       1, 2, 2, 2, 1, 0, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 4, 0, 2, 2, 3, 0,
       1, 2, 0, 0, 1, 4, 0, 0, 2, 3, 0, 0, 2, 0, 3, 2, 4, 2, 1, 0, 3, 3, 2,
       4, 2, 4, 1, 3, 3, 2, 4, 2, 2, 0, 4, 2, 2, 2, 3, 0, 0, 0, 1, 0, 1, 0,
       2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 3, 2, 2, 0, 1, 2, 1, 0, 2, 4, 1,
       2, 2, 4, 4, 2, 2, 2, 3, 4, 4, 4, 3, 0, 0, 2, 2, 2, 2, 4, 2, 4, 0, 3,
       2, 2, 2, 0, 1, 2, 0, 1, 0, 1, 3, 4, 0, 0, 3, 0, 4, 3, 2, 3, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 0, 4, 4, 2, 0, 2, 2, 0, 3, 1, 2, 4, 4, 3, 2,
       2, 3,

In [38]:
#computing for eighen faces 

In [39]:
n_components=150

In [40]:
n_components

150

In [42]:
print("Extraction top %d eighen from %d faces" %(n_components,X_train.shape[0]))

Extraction top 150 eighen from 855 faces


In [43]:
X_train.shape

(855, 1036)

In [44]:
start_time=time()

In [46]:
start_time

1515853438.8294988

In [47]:
#SVD single valued decomposition
#pca is simply regression type
#dimensional reduction
pca=PCA(n_components=n_components,svd_solver='randomized',whiten='True').fit(X_train)

In [48]:
pca

PCA(copy=True, iterated_power='auto', n_components=150, random_state=None,
  svd_solver='randomized', tol=0.0, whiten='True')

In [49]:
end_time=time()

In [60]:
X_train_pca=pca.transform(X_train)

In [61]:
X_test_pca=pca.transform(X_test)

In [52]:


print("time taken %0.4f s" %(end_time-start_time))

time taken 405.4586 s


In [53]:
#Train a SVM classification
# SVM is a classifier

In [54]:
start_time=time()

In [75]:
param_grid={'C':[1e3,5e3,1e4,5e4,1e5], 'gamma':[0.001,0.005,0.0001,]}
#list of dictionary

In [76]:
clf=GridSearchCV(SVC(kernel='rbf',class_weight='balanced'),param_grid)

In [77]:
clf

GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1000.0, 5000.0, 10000.0, 50000.0, 100000.0], 'gamma': [0.001, 0.005, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [78]:
clf=clf.fit(X_train_pca,y_train)

In [79]:
end_time=time()

In [80]:
print("the time taken %d" %(end_time-start_time))

the time taken 665


In [82]:
print("estimator by grid search")

estimator by grid search


In [84]:
print(clf.best_estimator_)

SVC(C=1000.0, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.005, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [85]:
# Quantative evalution on test set

In [86]:
print("Predicating people's name")

Predicating people's name


In [87]:
y_pred=clf.predict(X_test_pca)

In [89]:
print(classification_report(y_test,y_pred,target_names=target_names))

                   precision    recall  f1-score   support

     Colin Powell       0.95      0.94      0.94        64
  Donald Rumsfeld       1.00      0.84      0.92        32
    George W Bush       0.89      0.98      0.94       127
Gerhard Schroeder       1.00      0.86      0.93        29
       Tony Blair       0.97      0.88      0.92        33

      avg / total       0.94      0.93      0.93       285



In [91]:
print(confusion_matrix(y_test,y_pred,labels=range(n_classes)))

#to calculate error

[[ 60   0   4   0   0]
 [  0  27   4   0   1]
 [  2   0 125   0   0]
 [  1   0   3  25   0]
 [  0   0   4   0  29]]
